import { FC } from "react";
import { SvgDomesticCargo } from "../../../../helpers/svgs/boughtSvg";
import BoughtCard from "./BoughtCard";

const cardList = [
  {
    id: 1,
    orderID: "OhCaDwnom ",
    customer: "ShopMart",
    orderDate: "28.02.2022 - 14:20",
    total: "980.11",
    active: false,
    discount: 150,
    KDV: 350,
    deliveryDate: "2 Days Late",
    EReceipts: true,
    ShippingDetail: true,
    productList: [
      {
        id: 2,
        image: "/images/photos/StrepNaz Herbal.svg",
        name: "StrepNaz Orange &",
        brand: "Echinacea 24 Lozenges",
        miad: "March 2023",
        quantity: "15",
        price: "47.98",
        total: "$719.90",
      },
      {
        id: 3,
        image: "/images/photos/Oxygenated Water.svg",
        name: "HealthAid Oxygen Water",
        brand: "100 ml",
        miad: "March 2024",
        quantity: "25",
        price: "53.98",
        total: "$1325.00",
      },
      {
        id: 4,
        image: "/images/photos/Oxygenated Water.svg",
        name: "HealthAid Oxygen Water",
        brand: "100 ml",
        miad: "March 2024",
        quantity: "25",
        price: "53.98",
        total: "$1325.00",
      },
      {
        id: 5,
        image: "/images/photos/StrepNaz Herbal.svg",
        name: "StrepNaz Orange &",
        brand: "Echinacea 24 Lozenges",
        miad: "March 2023",
        quantity: "15",
        price: "47.98",
        total: "$719.90",
      },
    ],
    receiptInfo: {
      name: "Northwind Traders",
      taxID: "TX-18463408",
      taxOffice: "Central Tax Office",
      TCNo: "9000236566",
      address: "123 Commerce St, Suite 37, New York, NY 10001",
      email: "contact@northwind.example.com",
      active: true,
    },
    shippingInfo: {
      trackingNumber: "613364404629",
      image: <SvgDomesticCargo />,
      active: true,
    },
  },
  {
    id: 6,
    orderID: "AvTEyBXUq ",
    customer: "PlusStore",
    orderDate: "28.02.2022 - 14:20",
    total: "515.73",
    active: false,
    discount: 150,
    deliveryDate: "2 Days Late",
    KDV: 350,
    productList: [
      {
        id: 7,
        image: "/images/photos/StrepNaz Herbal.svg",
        name: "StrepNaz Orange &",
        brand: "Echinacea 24 Lozenges",
        miad: "March 2023",
        quantity: "15",
        price: "47.98",
        total: "$719.90",
      },
      {
        id: 8,
        image: "/images/photos/Oxygenated Water.svg",
        name: "HealthAid Oxygen Water",
        brand: "100 ml",
        miad: "March 2024",
        quantity: "25",
        price: "53.98",
        total: "$1325.00",
      },
    ],
    receiptInfo: {
      name: "Northwind Traders",
      taxID: "TX-18463408",
      taxOffice: "Central Tax Office",
      TCNo: "9000236566",
      address: "123 Commerce St, Suite 37, New York, NY 10001",
      email: "contact@northwind.example.com",
      active: true,
    },
    shippingInfo: {
      trackingNumber: "613364404629",
      image: <SvgDomesticCargo />,
      active: true,
    },
  },
  {
    id: 9,
    orderID: "OhCaDwnom",
    customer: "MediSupply",
    orderDate: "28.02.2022 - 14:20",
    total: "184.91",
    active: true,
    discount: 150,
    KDV: 350,
    deliveryDate: "2 Days Late",
    productList: [
      {
        id: 10,
        image: "/images/photos/StrepNaz Herbal.svg",
        name: "StrepNaz Orange &",
        brand: "Echinacea 24 Lozenges",
        miad: "March 2023",
        quantity: "15",
        price: "47.98",
        total: "$719.90",
      },
      {
        id: 11,
        image: "/images/photos/Oxygenated Water.svg",
        name: "HealthAid Oxygen Water",
        brand: "100 ml",
        miad: "March 2024",
        quantity: "25",
        price: "53.98",
        total: "$1325.00",
      },
    ],
    receiptInfo: {
      name: "Northwind Traders",
      taxID: "TX-18463408",
      taxOffice: "Central Tax Office",
      TCNo: "9000236566",
      address: "123 Commerce St, Suite 37, New York, NY 10001",
      email: "contact@northwind.example.com",
      active: true,
    },
    shippingInfo: {
      trackingNumber: "613364404629",
      image: <SvgDomesticCargo />,
      active: true,
    },
  },
  {
    id: 13,
    orderID: "OuYimVxdR",
    customer: "GreenLeaf Co",
    orderDate: "28.02.2022 - 14:20",
    total: "2535.50",
    active: false,
    discount: 150,
    KDV: 350,
    deliveryDate: "2 Days Late",
    productList: [
      {
        id: 14,
        image: "/images/photos/StrepNaz Herbal.svg",
        name: "StrepNaz Orange &",
        brand: "Echinacea 24 Lozenges",
        miad: "March 2023",
        quantity: "15",
        price: "47.98",
        total: "$719.90",
      },
      {
        id: 15,
        image: "/images/photos/Oxygenated Water.svg",
        name: "HealthAid Oxygen Water",
        brand: "100 ml",
        miad: "March 2024",
        quantity: "25",
        price: "53.98",
        total: "$1325.00",
      },
    ],
    receiptInfo: {
      name: "Northwind Traders",
      taxID: "TX-18463408",
      taxOffice: "Central Tax Office",
      TCNo: "9000236566",
      address: "123 Commerce St, Suite 37, New York, NY 10001",
      email: "contact@northwind.example.com",
      active: true,
    },
    shippingInfo: {
      trackingNumber: "613364404629",
      image: <SvgDomesticCargo />,
      active: true,
    },
  },
];

const WillBeShipped: FC = () => {
  return (
    <div className="grid gap-3 xl:gap-[0.75rem]">
      {cardList && cardList.map((content) => <BoughtCard key={content.id} content={content} />)}
    </div>
  );
};

export default WillBeShipped;
